# Generated by Django 6.1.1 on 2026-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(max_length=150)),
                ('profissao', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
    ]
